name: Build test - Windows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build'
        required: true
        default: 'staging'
env:
  PYTHONUNBUFFERED: 1

jobs:

  build:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Qt GUI with PySide6
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main_window.py
          mode: standalone
          enable-plugins: pyside6
          output-file: Fwitter
          msvc: latest
          include-data-dir: fonts
          include-data-dir: icons

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/
          include-hidden-files: true
